spring.application.name=coffriend-servidor

spring.datasource.url=${DATABASE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${DATABASE_USERNAME:sa}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driver-class-name=${DATABASE_DRIVER:org.h2.Driver}

<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update
=======
spring.jpa.hibernate.ddl-auto=create-drop
>>>>>>> parent of d5c611a (change app property ddl auto to create-update)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
spring.h2.console.enabled=true